import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Box } from '@mui/material';
import Image from 'next/image';
import Monkey from '@/images/monkey.png';

import Navigation from '@/components/Navigation/index';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Box
          sx={{
            position: 'relative',
          }}>
          {/* Image  */}
          <Box
            sx={{
              position: 'absolute',
              left: '215px',
            }}>
            <Image src={Monkey} width={120} height={120} alt='Monkey' />
          </Box>

          {/* Navigation  */}
          <Navigation />

          {/* Content Body  */}
          <Box
            sx={{
              maxWidth: '1070px',
              margin: '50px auto',
            }}>
            {children}
          </Box>
        </Box>
      </body>
    </html>
  );
}
